project_id = "vrcqnhksybtrfpagnwdq"

[functions.stripe-webhook]
verify_jwt = false

[functions.send-guest-invite]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.event-reminders-cron]
verify_jwt = false

[functions.auto-deactivate-events]
verify_jwt = false

[functions.auto-deactivate-guest-list-dates]
verify_jwt = false

[functions.validate-guest-registration]
verify_jwt = false

[functions.track-guest-list-analytics]
verify_jwt = false
