project_id = "vrcqnhksybtrfpagnwdq"

[functions.stripe-webhook]
verify_jwt = false

[functions.send-guest-invite]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.event-reminders-cron]
verify_jwt = false
